import { motion } from 'motion/react';
import {
  Coins,
  Flame,
  ShieldCheck,
  Layers3,
  ArrowUpRight,
  Wallet,
  Pickaxe,
  RefreshCw,
  LockKeyhole,
  Landmark,
  CheckCircle2,
  Sparkles,
  BarChart3,
  Database,
  Boxes,
  TrendingUp,
  Orbit,
  BadgeCheck,
  ArrowRightLeft,
} from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import './TokenomicsPage.css';

const supplyFacts = [
  {
    labelEn: 'Network',
    labelKo: '네트워크',
    value: 'TRON',
  },
  {
    labelEn: 'Total Supply',
    labelKo: '총발행량',
    value: '10,000,000,000 KORION',
  },
  {
    labelEn: 'Decimals',
    labelKo: '소수점',
    value: '6',
  },
];

const structureCards = [
  {
    icon: Pickaxe,
    titleEn: 'Reward Pool',
    titleKo: '리워드 풀',
    descEn:
      'A core portion of the supply is structured around reward and participation logic, including mobile mining and ecosystem contribution incentives.',
    descKo:
      '전체 공급 구조 중 핵심 물량은 모바일 채굴과 생태계 기여 보상을 포함한 리워드 및 참여 인센티브 중심으로 설계됩니다.',
  },
  {
    icon: TrendingUp,
    titleEn: 'Liquidity Layer',
    titleKo: '유동성 레이어',
    descEn:
      'Liquidity is designed to support market accessibility, smoother circulation, and healthier entry and exit conditions across trading environments.',
    descKo:
      '유동성 물량은 시장 접근성, 원활한 유통, 보다 안정적인 거래 환경을 지원하는 구조로 설계됩니다.',
  },
  {
    icon: LockKeyhole,
    titleEn: 'Cold Wallet Reserve',
    titleKo: '콜드월렛 리저브',
    descEn:
      'Strategic reserve assets can be separated from operational flows and managed for long-term security, treasury control, and supply discipline.',
    descKo:
      '전략 리저브 자산은 운영성 자금과 분리하여 장기 보안, 트레저리 통제, 공급 관리 목적에 맞게 운용될 수 있습니다.',
  },
  {
    icon: Wallet,
    titleEn: 'Operational Wallet Structure',
    titleKo: '운영 지갑 구조',
    descEn:
      'The token model is built to connect platform operations, internal circulation, settlement flows, and scalable ecosystem usage.',
    descKo:
      '토큰 구조는 플랫폼 운영, 내부 순환, 정산 흐름, 확장 가능한 생태계 사용처와 연결되도록 설계됩니다.',
  },
];

const utilityCards = [
  {
    icon: Wallet,
    titleEn: 'Platform Utility',
    titleKo: '플랫폼 실사용',
    descEn:
      'KORION is designed to function inside the platform economy, not merely as a transferable token. This includes ecosystem services, internal utility, and transactional use cases.',
    descKo:
      'KORION은 단순 전송용 토큰이 아니라 플랫폼 경제 안에서 실제로 작동하는 자산으로 설계됩니다. 여기에는 생태계 서비스, 내부 유틸리티, 거래 사용처가 포함됩니다.',
  },
  {
    icon: Pickaxe,
    titleEn: 'Mobile Mining Participation',
    titleKo: '모바일 채굴 참여',
    descEn:
      'Mobile mining logic is positioned as a user acquisition and participation mechanism, encouraging continuous engagement and ecosystem expansion.',
    descKo:
      '모바일 채굴 구조는 사용자 유입과 참여를 유도하는 핵심 장치로 작동하며, 지속적인 생태계 확장을 뒷받침합니다.',
  },
  {
    icon: RefreshCw,
    titleEn: 'Circulation & Reuse',
    titleKo: '순환 및 재사용',
    descEn:
      'KORION is intended to move through reward, holding, usage, settlement, and liquidity flows, forming an active circulation model rather than a static holding asset.',
    descKo:
      'KORION은 보상, 보유, 사용, 정산, 유동성 흐름을 거치며 순환하도록 설계되어 정적인 보관형 자산이 아닌 실제 순환형 모델을 지향합니다.',
  },
  {
    icon: Flame,
    titleEn: 'Monthly Burn Logic',
    titleKo: '월간 소각 구조',
    descEn:
      '10% of monthly revenue generated by the operating platform is designed to be burned on a regular basis, reinforcing scarcity as ecosystem activity grows.',
    descKo:
      '자체 운영 플랫폼에서 발생한 월 수익의 10%를 정기적으로 소각하는 구조를 통해 생태계가 성장할수록 희소성을 강화하는 방향을 지향합니다.',
  },
];

const flowSteps = [
  {
    step: '01',
    titleEn: 'Initial Supply Framework',
    titleKo: '초기 공급 프레임',
    descEn:
      'KORION begins from a defined total supply framework on TRON, with operational categories such as reward, liquidity, reserve, and platform-related allocation logic.',
    descKo:
      'KORION은 TRON 기반의 총발행량 구조를 바탕으로 시작하며, 리워드, 유동성, 리저브, 플랫폼 운영 목적의 공급 카테고리로 구성됩니다.',
  },
  {
    step: '02',
    titleEn: 'User Participation Entry',
    titleKo: '사용자 참여 유입',
    descEn:
      'Users can enter the ecosystem through wallet activity, mobile mining participation, service onboarding, and other ecosystem touchpoints.',
    descKo:
      '사용자는 지갑 활동, 모바일 채굴 참여, 서비스 온보딩, 기타 생태계 접점을 통해 KORION 생태계로 유입됩니다.',
  },
  {
    step: '03',
    titleEn: 'Utility Activation',
    titleKo: '실사용 활성화',
    descEn:
      'The token gains practical meaning when used inside the platform for service flows, payments, internal transactions, and ecosystem-linked value exchange.',
    descKo:
      '토큰은 플랫폼 안에서 서비스 흐름, 결제, 내부 거래, 생태계 연동 가치 교환에 사용될 때 실질적인 의미를 갖게 됩니다.',
  },
  {
    step: '04',
    titleEn: 'Revenue-Linked Scarcity',
    titleKo: '수익 연동 희소성',
    descEn:
      'As the platform expands, monthly revenue-linked burn mechanics help recycle value back into supply discipline and long-term sustainability.',
    descKo:
      '플랫폼이 확장될수록 월 수익 연동 소각 구조가 공급 통제와 장기 지속 가능성으로 다시 연결되는 흐름을 형성합니다.',
  },
];

const governanceItems = [
  {
    icon: ShieldCheck,
    titleEn: 'Treasury Discipline',
    titleKo: '트레저리 운영 원칙',
    descEn:
      'Long-term trust depends on disciplined reserve management and clear separation between strategic assets and daily operations.',
    descKo:
      '장기 신뢰는 전략 자산과 일상 운영 자산을 분리하고 일관된 원칙으로 관리하는 데서 형성됩니다.',
  },
  {
    icon: Database,
    titleEn: 'Expandable Token Structure',
    titleKo: '확장 가능한 발행 구조',
    descEn:
      'The supply model is designed with the possibility of future change or additional issuance, making governance transparency especially important.',
    descKo:
      '공급 구조는 향후 변경 및 추가 발행 가능성을 포함하고 있기 때문에, 운영 투명성과 거버넌스 원칙이 더욱 중요합니다.',
  },
  {
    icon: Landmark,
    titleEn: 'Real-Economy Orientation',
    titleKo: '실물형 생태계 지향',
    descEn:
      'The token model is aimed at supporting real platform activity, service usage, and internal ecosystem value exchange rather than relying only on market speculation.',
    descKo:
      '토큰 구조는 단순 시세 중심이 아니라 플랫폼 실사용, 서비스 이용, 내부 생태계 가치 교환을 뒷받침하는 방향을 지향합니다.',
  },
];

const supplyModelStats = [
  {
    labelEn: 'Total Supply Framework',
    labelKo: '총공급 프레임',
    value: '10B',
    subEn: 'KORION',
    subKo: 'KORION',
  },
  {
    labelEn: 'Revenue Burn Rule',
    labelKo: '수익 소각 규칙',
    value: '10%',
    subEn: 'Monthly Platform Revenue',
    subKo: '월 플랫폼 수익',
  },
  {
    labelEn: 'Settlement Base',
    labelKo: '기반 네트워크',
    value: 'TRON',
    subEn: 'TRC-Based Ecosystem',
    subKo: 'TRC 기반 생태계',
  },
  {
    labelEn: 'Precision',
    labelKo: '소수점 체계',
    value: '6',
    subEn: 'Token Decimals',
    subKo: '토큰 소수점',
  },
];

const burnSimulationRows = [
  {
    scenarioEn: 'Early Stage',
    scenarioKo: '초기 단계',
    revenue: '$50,000',
    burn: '$5,000',
    effectEn: 'Light but steady burn pressure begins to build token scarcity.',
    effectKo: '작지만 지속적인 소각 압력이 형성되며 희소성이 시작됩니다.',
  },
  {
    scenarioEn: 'Growth Stage',
    scenarioKo: '성장 단계',
    revenue: '$250,000',
    burn: '$25,000',
    effectEn: 'Platform expansion starts producing visible deflationary effects.',
    effectKo: '플랫폼 성장에 따라 체감 가능한 디플레이션 효과가 나타나기 시작합니다.',
  },
  {
    scenarioEn: 'Scale Stage',
    scenarioKo: '확장 단계',
    revenue: '$1,000,000',
    burn: '$100,000',
    effectEn: 'Revenue-linked burn becomes a major long-term scarcity driver.',
    effectKo: '수익 연동 소각이 장기 희소성의 핵심 축으로 작동하게 됩니다.',
  },
];

const walletArchitecture = [
  {
    key: 'reward',
    titleEn: 'Reward Pool',
    titleKo: '리워드 풀',
    descEn:
      'Used for mining rewards, participation incentives, and ecosystem activity distribution.',
    descKo:
      '채굴 보상, 참여 인센티브, 생태계 활동 보상 분배에 사용되는 핵심 리워드 영역입니다.',
  },
  {
    key: 'liquidity',
    titleEn: 'Liquidity Wallet',
    titleKo: '유동성 지갑',
    descEn:
      'Supports market accessibility, smoother swaps, and trading environment stability.',
    descKo:
      '시장 접근성, 원활한 스왑, 거래 환경의 안정성을 지원하는 유동성 영역입니다.',
  },
  {
    key: 'hot',
    titleEn: 'Hot Wallet',
    titleKo: '핫월렛',
    descEn:
      'Handles active operational movement, platform processing, and live transaction flows.',
    descKo:
      '실시간 운영 이동, 플랫폼 처리, 활성 거래 흐름을 담당하는 운영 지갑입니다.',
  },
  {
    key: 'cold',
    titleEn: 'Cold Wallet',
    titleKo: '콜드월렛',
    descEn:
      'Protects strategic reserves with stronger isolation for long-term treasury security.',
    descKo:
      '장기 트레저리 보안을 위해 전략 리저브를 보다 강하게 분리 보관하는 구조입니다.',
  },
  {
    key: 'platform',
    titleEn: 'Platform Utility',
    titleKo: '플랫폼 유틸리티',
    descEn:
      'Connects token use with services, payments, internal value exchange, and product activity.',
    descKo:
      '서비스, 결제, 내부 가치 교환, 제품 활동과 토큰 사용을 연결하는 실사용 영역입니다.',
  },
  {
    key: 'burn',
    titleEn: 'Burn Engine',
    titleKo: '소각 엔진',
    descEn:
      'Executes regular supply reduction based on 10% of monthly platform revenue.',
    descKo:
      '월 플랫폼 수익의 10%를 기준으로 정기적인 공급 감소를 수행하는 소각 구조입니다.',
  },
];

export function TokenomicsPage() {
  const { language } = useLanguage();
  const isKo = language === 'KR';

  return (
    <div className="tokenomics-page">
      <div className="tokenomics-page__ambient">
        <span className="tokenomics-page__orb tokenomics-page__orb--1" />
        <span className="tokenomics-page__orb tokenomics-page__orb--2" />
        <span className="tokenomics-page__orb tokenomics-page__orb--3" />
        <span className="tokenomics-page__beam tokenomics-page__beam--1" />
        <span className="tokenomics-page__beam tokenomics-page__beam--2" />
      </div>

      <section className="tokenomics-hero">
        <div className="tokenomics-page__container">
          <div className="tokenomics-hero__grid">
            <motion.div
              className="tokenomics-hero__content"
              initial={{ opacity: 0, y: 26 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.25 }}
              transition={{ duration: 0.7 }}
            >
              <div className="tokenomics-hero__eyebrow">
                <Sparkles size={14} />
                <span>{isKo ? 'KORION 공급 및 활용 모델' : 'KORION Supply & Utility Model'}</span>
              </div>

              <h1 className="tokenomics-hero__title">
                {isKo
                  ? '실사용, 참여, 희소성이 하나로 연결되는 KORION 토크노믹스'
                  : 'A Premium Tokenomics Model Connecting Utility, Participation, and Scarcity'}
              </h1>

              <p className="tokenomics-hero__desc">
                {isKo
                  ? 'KORION은 TRON 기반으로 설계된 디지털 자산으로, 단순 보유형 토큰이 아니라 모바일 채굴 참여, 플랫폼 내부 실사용, 생태계 거래, 유동성 순환, 그리고 월 수익 10% 정기 소각 구조를 통해 장기적 가치를 강화하는 방향을 지향합니다.'
                  : 'KORION is built on TRON as a utility-oriented digital asset designed to connect mobile mining participation, internal platform usage, ecosystem circulation, market accessibility, and revenue-linked burn mechanics.'}
              </p>

              <div className="tokenomics-hero__stats">
                {supplyFacts.map((item) => (
                  <div key={item.labelEn} className="tokenomics-stat">
                    <span className="tokenomics-stat__label">
                      {isKo ? item.labelKo : item.labelEn}
                    </span>
                    <strong className="tokenomics-stat__value">{item.value}</strong>
                  </div>
                ))}
              </div>

              <div className="tokenomics-hero__featureline">
                <div className="tokenomics-hero__featurepill">
                  <BadgeCheck size={16} />
                  <span>{isKo ? '실사용 중심 설계' : 'Utility-Focused Design'}</span>
                </div>
                <div className="tokenomics-hero__featurepill">
                  <Orbit size={16} />
                  <span>{isKo ? '순환형 경제 모델' : 'Circular Economy Model'}</span>
                </div>
                <div className="tokenomics-hero__featurepill">
                  <Flame size={16} />
                  <span>{isKo ? '월 수익 10% 소각' : '10% Monthly Burn'}</span>
                </div>
              </div>
            </motion.div>

            <motion.div
              className="tokenomics-hero__visual"
              initial={{ opacity: 0, scale: 0.96 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true, amount: 0.25 }}
              transition={{ duration: 0.8 }}
            >
              <div className="tokenomics-orbit">
                <div className="tokenomics-orbit__glow" />
                <div className="tokenomics-orbit__ring tokenomics-orbit__ring--outer" />
                <div className="tokenomics-orbit__ring tokenomics-orbit__ring--mid" />
                <div className="tokenomics-orbit__ring tokenomics-orbit__ring--inner" />

                <div className="tokenomics-orbit__pulse tokenomics-orbit__pulse--1" />
                <div className="tokenomics-orbit__pulse tokenomics-orbit__pulse--2" />

                <div className="tokenomics-orbit__core">
                  <div className="tokenomics-orbit__core-badge">
                    <Coins size={20} />
                    <span>KORION</span>
                  </div>
                  <h3>{isKo ? '토큰 유틸리티 순환 구조' : 'Utility Circulation Engine'}</h3>
                  <p>
                    {isKo
                      ? '공급 → 참여 → 실사용 → 순환 → 소각으로 이어지는 가치 흐름'
                      : 'A connected value loop from supply to participation, utility, circulation, and burn'}
                  </p>
                </div>

                <div className="tokenomics-orbit__node tokenomics-orbit__node--a">
                  <Pickaxe size={16} />
                  <span>{isKo ? '채굴' : 'Mining'}</span>
                </div>
                <div className="tokenomics-orbit__node tokenomics-orbit__node--b">
                  <Wallet size={16} />
                  <span>{isKo ? '유틸리티' : 'Utility'}</span>
                </div>
                <div className="tokenomics-orbit__node tokenomics-orbit__node--c">
                  <ArrowUpRight size={16} />
                  <span>{isKo ? '유동성' : 'Liquidity'}</span>
                </div>
                <div className="tokenomics-orbit__node tokenomics-orbit__node--d">
                  <Flame size={16} />
                  <span>{isKo ? '소각' : 'Burn'}</span>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <section className="tokenomics-section">
        <div className="tokenomics-page__container-01">
          <motion.div
            className="tokenomics-section__heading"
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.25 }}
            transition={{ duration: 0.65 }}
          >
            <span className="tokenomics-section__eyebrow">
              <Layers3 size={15} />
              {isKo ? 'Supply Structure' : 'Supply Structure'}
            </span>
            <h2>
              {isKo
                ? 'KORION 공급 구조의 핵심 축'
                : 'The Core Structural Pillars of the KORION Supply Model'}
            </h2>
            <p>
              {isKo
                ? 'KORION의 공급 구조는 단순 분배표보다, 실제 운영과 장기 생태계 확장을 위한 역할 중심 설계에 가깝습니다. 리워드, 유동성, 리저브, 운영 지갑 구조가 서로 분리되면서도 하나의 순환 모델 안에서 연결됩니다.'
                : 'Rather than operating as a static issuance table, the KORION supply framework is designed around real functional roles across rewards, liquidity, reserves, and platform-level circulation.'}
            </p>
          </motion.div>

          <div className="tokenomics-utility__grid">
            {structureCards.map((item, index) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={item.titleEn}
                  className="tokenomics-utility__card"
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.15 }}
                  transition={{ duration: 0.55, delay: index * 0.06 }}
                >
                  <div className="tokenomics-utility__icon">
                    <Icon size={20} />
                  </div>
                  <h3>{isKo ? item.titleKo : item.titleEn}</h3>
                  <p>{isKo ? item.descKo : item.descEn}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="tokenomics-section tokenomics-section--alt">
        <div className="tokenomics-page__container-01">
          <div className="tokenomics-utility">
            <motion.div
              className="tokenomics-utility__left"
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, amount: 0.25 }}
              transition={{ duration: 0.7 }}
            >
              <span className="tokenomics-section__eyebrow">
                <BarChart3 size={15} />
                {isKo ? 'Utility Architecture' : 'Utility Architecture'}
              </span>
              <h2>
                {isKo
                  ? 'KORION은 보유보다 사용될 때 더 강해집니다'
                  : 'KORION Becomes Stronger When It Is Used, Not Merely Held'}
              </h2>
              <p>
                {isKo
                  ? 'KORION 토크노믹스의 핵심은 단순 공급량 자체가 아니라, 실제 사용 구조입니다. 지갑, 플랫폼, 내부 거래, 채굴 참여, 리워드 순환, 유동성, 그리고 수익 연동 소각까지 이어질 때 비로소 토큰 경제가 작동합니다.'
                  : 'The real strength of KORION lies not in static supply metrics but in active usage. Wallet interactions, internal platform utility, mining participation, rewards, liquidity, and burn-linked value recycling together define the token economy.'}
              </p>

              <div className="tokenomics-feature-points">
                <div className="tokenomics-feature-point">
                  <CheckCircle2 size={18} />
                  <span>
                    {isKo
                      ? '모바일 채굴과 사용자 참여 중심 유입 구조'
                      : 'Participation-driven onboarding through mobile mining'}
                  </span>
                </div>
                <div className="tokenomics-feature-point">
                  <CheckCircle2 size={18} />
                  <span>
                    {isKo
                      ? '플랫폼 내부 거래와 서비스에 연결되는 실사용 구조'
                      : 'Real utility connected to platform services and transactions'}
                  </span>
                </div>
                <div className="tokenomics-feature-point">
                  <CheckCircle2 size={18} />
                  <span>
                    {isKo
                      ? '월 수익 10% 소각을 통한 장기 희소성 강화'
                      : 'Long-term scarcity reinforced by 10% monthly revenue burn'}
                  </span>
                </div>
              </div>
            </motion.div>

            <div className="tokenomics-utility__grid">
              {utilityCards.map((item, index) => {
                const Icon = item.icon;
                return (
                  <motion.div
                    key={item.titleEn}
                    className="tokenomics-utility__card"
                    initial={{ opacity: 0, y: 24 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, amount: 0.15 }}
                    transition={{ duration: 0.55, delay: index * 0.06 }}
                  >
                    <div className="tokenomics-utility__icon">
                      <Icon size={20} />
                    </div>
                    <h3>{isKo ? item.titleKo : item.titleEn}</h3>
                    <p>{isKo ? item.descKo : item.descEn}</p>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      <section className="tokenomics-section">
        <div className="tokenomics-page__container-01">
          <motion.div
            className="tokenomics-section__heading"
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.65 }}
          >
            <span className="tokenomics-section__eyebrow">
              <ArrowRightLeft size={15} />
              {isKo ? 'Value Flow' : 'Value Flow'}
            </span>
            <h2>
              {isKo
                ? 'KORION 가치가 순환하는 방식'
                : 'How Value Circulates Through the KORION Ecosystem'}
            </h2>
            <p>
              {isKo
                ? 'KORION은 발행 이후 정체되는 구조가 아니라, 참여와 사용을 통해 가치를 순환시키고, 플랫폼 수익과 연결된 소각을 통해 공급의 질을 관리하는 흐름을 지향합니다.'
                : 'KORION is designed to circulate through active participation and real utility, with value recycling strengthened through platform-linked burn mechanics.'}
            </p>
          </motion.div>

          <div className="tokenomics-flow">
            {flowSteps.map((item, index) => (
              <motion.div
                key={item.step}
                className="tokenomics-flow__item"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.15 }}
                transition={{ duration: 0.5, delay: index * 0.05 }}
              >
                <div className="tokenomics-flow__step">{item.step}</div>
                <h3>{isKo ? item.titleKo : item.titleEn}</h3>
                <p>{isKo ? item.descKo : item.descEn}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="tokenomics-section tokenomics-section--alt">
        <div className="tokenomics-page__container-01">
          <div className="tokenomics-governance">
            <motion.div
              className="tokenomics-governance__panel"
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.7 }}
            >
              <span className="tokenomics-section__eyebrow">
                <ShieldCheck size={15} />
                {isKo ? 'Governance & Sustainability' : 'Governance & Sustainability'}
              </span>
              <h2>
                {isKo
                  ? '핵심은 공급량보다 운영 신뢰입니다'
                  : 'Long-Term Confidence Depends More on Governance Than on Supply Alone'}
              </h2>
              <p>
                {isKo
                  ? 'KORION은 향후 변경 및 추가 발행 가능 구조를 포함하고 있기 때문에, 단순 숫자보다 운영 원칙과 투명성이 더욱 중요합니다. 리저브 관리, 유동성 운영, 생태계 확장, 소각 정책이 일관되게 작동해야 장기 신뢰가 형성됩니다.'
                  : 'Because the token framework allows future change or additional issuance, transparency and operational discipline matter even more. Reserve policy, liquidity behavior, ecosystem expansion, and burn execution together shape market trust.'}
              </p>

              <div className="tokenomics-governance__items">
                {governanceItems.map((item) => {
                  const Icon = item.icon;
                  return (
                    <div key={item.titleEn} className="tokenomics-governance__item">
                      <div className="tokenomics-governance__icon">
                        <Icon size={18} />
                      </div>
                      <div>
                        <h3>{isKo ? item.titleKo : item.titleEn}</h3>
                        <p>{isKo ? item.descKo : item.descEn}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </motion.div>

            <motion.div
              className="tokenomics-summary-card"
              initial={{ opacity: 0, scale: 0.97 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.7 }}
            >
              <div className="tokenomics-summary-card__badge">
                <Boxes size={16} />
                <span>{isKo ? 'KORION Summary' : 'KORION Summary'}</span>
              </div>

              <h3>
                {isKo
                  ? 'KORION은 TRON 기반 100억 공급 구조 위에, 모바일 채굴 참여와 플랫폼 실사용, 그리고 월 수익 10% 소각을 연결한 순환형 생태계 자산입니다.'
                  : 'KORION is a TRON-based ecosystem asset built on a 10 billion supply framework, connecting mobile mining participation, platform utility, and a 10% monthly revenue burn model.'}
              </h3>

              <ul className="tokenomics-summary-card__list">
                <li>
                  {isKo
                    ? 'TRON 기반 / 총발행량 10,000,000,000 / 소수점 6자리'
                    : 'TRON-based / 10,000,000,000 total supply / 6 decimals'}
                </li>
                <li>
                  {isKo
                    ? '리워드·유동성·리저브·운영 구조 중심의 공급 설계'
                    : 'Supply architecture centered on rewards, liquidity, reserves, and operations'}
                </li>
                <li>
                  {isKo
                    ? '플랫폼 내부 실제 사용 및 생태계 거래를 위한 설계'
                    : 'Designed for real platform utility and ecosystem-level transactions'}
                </li>
                <li>
                  {isKo
                    ? '운영 플랫폼 월 수익의 10% 정기 소각 구조'
                    : 'Regular burn structure based on 10% of monthly platform revenue'}
                </li>
                <li>
                  {isKo
                    ? '향후 변경 및 추가 발행 가능성을 포함한 확장형 모델'
                    : 'Expandable framework allowing future modification and additional issuance'}
                </li>
              </ul>

              <div className="tokenomics-summary-card__footer">
                <span>{isKo ? 'KORION 생태계를 위해 설계된 구조' : 'Built for the KORION ecosystem'}</span>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <section className="tokenomics-section">
        <div className="tokenomics-page__container-01">
          <motion.div
            className="tokenomics-section__heading"
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.65 }}
          >
            <span className="tokenomics-section__eyebrow">
              <BarChart3 size={15} />
              {isKo ? 'Supply Metrics' : 'Supply Metrics'}
            </span>
            <h2>
              {isKo
                ? '핵심 수치로 보는 KORION 공급 모델'
                : 'The KORION Supply Model at a Glance'}
            </h2>
            <p>
              {isKo
                ? 'KORION의 공급 구조는 단순 발행 수치보다, 운영 구조와 수익 환류 메커니즘까지 포함한 입체적 모델입니다. 아래 지표는 KORION 토크노믹스의 핵심 기반을 빠르게 보여줍니다.'
                : 'KORION is defined not only by issuance numbers but by how supply, revenue recycling, and operational design work together over time.'}
            </p>
          </motion.div>

          <div className="tokenomics-supply-metrics">
            {supplyModelStats.map((item, index) => (
              <motion.div
                key={item.labelEn}
                className="tokenomics-supply-metric"
                initial={{ opacity: 0, y: 22 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.15 }}
                transition={{ duration: 0.55, delay: index * 0.05 }}
              >
                <span className="tokenomics-supply-metric__label">
                  {isKo ? item.labelKo : item.labelEn}
                </span>
                <strong className="tokenomics-supply-metric__value">{item.value}</strong>
                <span className="tokenomics-supply-metric__sub">
                  {isKo ? item.subKo : item.subEn}
                </span>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="tokenomics-section tokenomics-section--alt">
        <div className="tokenomics-page__container-01">
          <div className="tokenomics-burn">
            <motion.div
              className="tokenomics-burn__left"
              initial={{ opacity: 0, x: -18 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.65 }}
            >
              <span className="tokenomics-section__eyebrow">
                <Flame size={15} />
                {isKo ? 'Burn Simulation' : 'Burn Simulation'}
              </span>
              <h2>
                {isKo
                  ? '월 수익 10% 소각이 만드는 장기 희소성'
                  : 'How the 10% Monthly Revenue Burn Can Build Long-Term Scarcity'}
              </h2>
              <p>
                {isKo
                  ? 'KORION은 운영 플랫폼에서 발생한 월 수익의 10%를 정기적으로 소각하는 구조를 기반으로 합니다. 이 구조는 플랫폼 규모가 커질수록 단순한 마케팅 장치가 아니라 실제 공급 감소 메커니즘으로 작동할 수 있습니다.'
                  : 'KORION links 10% of monthly operating platform revenue to a recurring burn mechanism, allowing ecosystem growth to reinforce supply discipline over time.'}
              </p>

              <div className="tokenomics-feature-points">
                <div className="tokenomics-feature-point">
                  <CheckCircle2 size={18} />
                  <span>
                    {isKo
                      ? '플랫폼 성장과 토큰 희소성이 연결되는 구조'
                      : 'Platform growth and token scarcity become directly connected'}
                  </span>
                </div>
                <div className="tokenomics-feature-point">
                  <CheckCircle2 size={18} />
                  <span>
                    {isKo
                      ? '정적 공급 모델이 아닌 수익 환류형 구조'
                      : 'A revenue-recycling model rather than a static issuance structure'}
                  </span>
                </div>
                <div className="tokenomics-feature-point">
                  <CheckCircle2 size={18} />
                  <span>
                    {isKo
                      ? '장기 생태계 신뢰를 강화하는 디플레이션 설계'
                      : 'Deflation-oriented design that can strengthen long-term confidence'}
                  </span>
                </div>
              </div>
            </motion.div>

            <motion.div
              className="tokenomics-burn__tableWrap"
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.65 }}
            >
              <div className="tokenomics-burn__table">
                <div className="tokenomics-burn__head">
                  <span>{isKo ? '단계' : 'Stage'}</span>
                  <span>{isKo ? '월 수익 예시' : 'Monthly Revenue'}</span>
                  <span>{isKo ? '월 소각 예시' : 'Monthly Burn'}</span>
                </div>

                {burnSimulationRows.map((row) => (
                  <div key={row.scenarioEn} className="tokenomics-burn__row">
                    <span>{isKo ? row.scenarioKo : row.scenarioEn}</span>
                    <span>{row.revenue}</span>
                    <span>{row.burn}</span>
                    <p>{isKo ? row.effectKo : row.effectEn}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <section className="tokenomics-section">
        <div className="tokenomics-page__container-01">
          <motion.div
            className="tokenomics-section__heading"
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.65 }}
          >
            <span className="tokenomics-section__eyebrow">
              <Database size={15} />
              {isKo ? 'Wallet Architecture' : 'Wallet Architecture'}
            </span>
            <h2>
              {isKo
                ? 'KORION 공급과 활용을 연결하는 지갑 아키텍처'
                : 'The Wallet Architecture Behind KORION Supply and Utility'}
            </h2>
            <p>
              {isKo
                ? 'KORION의 토크노믹스는 단순 수치가 아니라 실제 운영 구조와 연결되어야 합니다. 리워드 풀, 유동성, 핫월렛, 콜드월렛, 플랫폼 유틸리티, 소각 엔진은 각각 독립된 역할을 가지면서도 하나의 순환 체계 안에서 맞물립니다.'
                : 'KORION tokenomics should not exist only on paper. Reward pools, liquidity, hot wallet operations, cold storage, platform utility, and burn logic must function as a connected architecture.'}
            </p>
          </motion.div>

          <div className="tokenomics-architecture">
            <div className="tokenomics-architecture__center">
              <div className="tokenomics-architecture__core">
                <Coins size={28} />
                <strong>KORION</strong>
                <span>{isKo ? 'Supply & Utility Core' : 'Supply & Utility Core'}</span>
              </div>
            </div>

            <div className="tokenomics-architecture__grid">
              {walletArchitecture.map((item, index) => (
                <motion.div
                  key={item.key}
                  className={`tokenomics-architecture__node tokenomics-architecture__node--${item.key}`}
                  initial={{ opacity: 0, scale: 0.94 }}
                  whileInView={{ opacity: 1, scale: 1 }}
                  viewport={{ once: true, amount: 0.15 }}
                  transition={{ duration: 0.45, delay: index * 0.04 }}
                >
                  <h3>{isKo ? item.titleKo : item.titleEn}</h3>
                  <p>{isKo ? item.descKo : item.descEn}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
